################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../platform/thinkey_security_al/mbedtls/source/aes.c \
../platform/thinkey_security_al/mbedtls/source/aesni.c \
../platform/thinkey_security_al/mbedtls/source/ansi_x936_kdf.c \
../platform/thinkey_security_al/mbedtls/source/arc4.c \
../platform/thinkey_security_al/mbedtls/source/aria.c \
../platform/thinkey_security_al/mbedtls/source/asn1parse.c \
../platform/thinkey_security_al/mbedtls/source/asn1write.c \
../platform/thinkey_security_al/mbedtls/source/base64.c \
../platform/thinkey_security_al/mbedtls/source/bignum.c \
../platform/thinkey_security_al/mbedtls/source/blowfish.c \
../platform/thinkey_security_al/mbedtls/source/camellia.c \
../platform/thinkey_security_al/mbedtls/source/ccm.c \
../platform/thinkey_security_al/mbedtls/source/certs.c \
../platform/thinkey_security_al/mbedtls/source/chacha20.c \
../platform/thinkey_security_al/mbedtls/source/chachapoly.c \
../platform/thinkey_security_al/mbedtls/source/cipher.c \
../platform/thinkey_security_al/mbedtls/source/cipher_wrap.c \
../platform/thinkey_security_al/mbedtls/source/cmac.c \
../platform/thinkey_security_al/mbedtls/source/ctr_drbg.c \
../platform/thinkey_security_al/mbedtls/source/debug.c \
../platform/thinkey_security_al/mbedtls/source/des.c \
../platform/thinkey_security_al/mbedtls/source/dhm.c \
../platform/thinkey_security_al/mbedtls/source/ecdh.c \
../platform/thinkey_security_al/mbedtls/source/ecdsa.c \
../platform/thinkey_security_al/mbedtls/source/ecjpake.c \
../platform/thinkey_security_al/mbedtls/source/ecp.c \
../platform/thinkey_security_al/mbedtls/source/ecp_curves.c \
../platform/thinkey_security_al/mbedtls/source/entropy.c \
../platform/thinkey_security_al/mbedtls/source/entropy_poll.c \
../platform/thinkey_security_al/mbedtls/source/error.c \
../platform/thinkey_security_al/mbedtls/source/gcm.c \
../platform/thinkey_security_al/mbedtls/source/havege.c \
../platform/thinkey_security_al/mbedtls/source/hkdf.c \
../platform/thinkey_security_al/mbedtls/source/hmac_drbg.c \
../platform/thinkey_security_al/mbedtls/source/md.c \
../platform/thinkey_security_al/mbedtls/source/md2.c \
../platform/thinkey_security_al/mbedtls/source/md4.c \
../platform/thinkey_security_al/mbedtls/source/md5.c \
../platform/thinkey_security_al/mbedtls/source/memory_buffer_alloc.c \
../platform/thinkey_security_al/mbedtls/source/net_sockets.c \
../platform/thinkey_security_al/mbedtls/source/nist_kw.c \
../platform/thinkey_security_al/mbedtls/source/oid.c \
../platform/thinkey_security_al/mbedtls/source/padlock.c \
../platform/thinkey_security_al/mbedtls/source/pem.c \
../platform/thinkey_security_al/mbedtls/source/pk.c \
../platform/thinkey_security_al/mbedtls/source/pk_wrap.c \
../platform/thinkey_security_al/mbedtls/source/pkcs11.c \
../platform/thinkey_security_al/mbedtls/source/pkcs12.c \
../platform/thinkey_security_al/mbedtls/source/pkcs5.c \
../platform/thinkey_security_al/mbedtls/source/pkparse.c \
../platform/thinkey_security_al/mbedtls/source/pkwrite.c \
../platform/thinkey_security_al/mbedtls/source/platform.c \
../platform/thinkey_security_al/mbedtls/source/platform_util.c \
../platform/thinkey_security_al/mbedtls/source/poly1305.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_client.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_driver_wrappers.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_ecp.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_rsa.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_se.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_slot_management.c \
../platform/thinkey_security_al/mbedtls/source/psa_crypto_storage.c \
../platform/thinkey_security_al/mbedtls/source/psa_its_file.c \
../platform/thinkey_security_al/mbedtls/source/ripemd160.c \
../platform/thinkey_security_al/mbedtls/source/rsa.c \
../platform/thinkey_security_al/mbedtls/source/rsa_internal.c \
../platform/thinkey_security_al/mbedtls/source/sha1.c \
../platform/thinkey_security_al/mbedtls/source/sha256.c \
../platform/thinkey_security_al/mbedtls/source/sha512.c \
../platform/thinkey_security_al/mbedtls/source/ssl_cache.c \
../platform/thinkey_security_al/mbedtls/source/ssl_ciphersuites.c \
../platform/thinkey_security_al/mbedtls/source/ssl_cli.c \
../platform/thinkey_security_al/mbedtls/source/ssl_cookie.c \
../platform/thinkey_security_al/mbedtls/source/ssl_msg.c \
../platform/thinkey_security_al/mbedtls/source/ssl_srv.c \
../platform/thinkey_security_al/mbedtls/source/ssl_ticket.c \
../platform/thinkey_security_al/mbedtls/source/ssl_tls.c \
../platform/thinkey_security_al/mbedtls/source/ssl_tls13_keys.c \
../platform/thinkey_security_al/mbedtls/source/threading.c \
../platform/thinkey_security_al/mbedtls/source/timing.c \
../platform/thinkey_security_al/mbedtls/source/version.c \
../platform/thinkey_security_al/mbedtls/source/version_features.c \
../platform/thinkey_security_al/mbedtls/source/x509.c \
../platform/thinkey_security_al/mbedtls/source/x509_create.c \
../platform/thinkey_security_al/mbedtls/source/x509_crl.c \
../platform/thinkey_security_al/mbedtls/source/x509_crt.c \
../platform/thinkey_security_al/mbedtls/source/x509_csr.c \
../platform/thinkey_security_al/mbedtls/source/x509write_crt.c \
../platform/thinkey_security_al/mbedtls/source/x509write_csr.c \
../platform/thinkey_security_al/mbedtls/source/xtea.c 

C_DEPS += \
./platform/thinkey_security_al/mbedtls/source/aes.d \
./platform/thinkey_security_al/mbedtls/source/aesni.d \
./platform/thinkey_security_al/mbedtls/source/ansi_x936_kdf.d \
./platform/thinkey_security_al/mbedtls/source/arc4.d \
./platform/thinkey_security_al/mbedtls/source/aria.d \
./platform/thinkey_security_al/mbedtls/source/asn1parse.d \
./platform/thinkey_security_al/mbedtls/source/asn1write.d \
./platform/thinkey_security_al/mbedtls/source/base64.d \
./platform/thinkey_security_al/mbedtls/source/bignum.d \
./platform/thinkey_security_al/mbedtls/source/blowfish.d \
./platform/thinkey_security_al/mbedtls/source/camellia.d \
./platform/thinkey_security_al/mbedtls/source/ccm.d \
./platform/thinkey_security_al/mbedtls/source/certs.d \
./platform/thinkey_security_al/mbedtls/source/chacha20.d \
./platform/thinkey_security_al/mbedtls/source/chachapoly.d \
./platform/thinkey_security_al/mbedtls/source/cipher.d \
./platform/thinkey_security_al/mbedtls/source/cipher_wrap.d \
./platform/thinkey_security_al/mbedtls/source/cmac.d \
./platform/thinkey_security_al/mbedtls/source/ctr_drbg.d \
./platform/thinkey_security_al/mbedtls/source/debug.d \
./platform/thinkey_security_al/mbedtls/source/des.d \
./platform/thinkey_security_al/mbedtls/source/dhm.d \
./platform/thinkey_security_al/mbedtls/source/ecdh.d \
./platform/thinkey_security_al/mbedtls/source/ecdsa.d \
./platform/thinkey_security_al/mbedtls/source/ecjpake.d \
./platform/thinkey_security_al/mbedtls/source/ecp.d \
./platform/thinkey_security_al/mbedtls/source/ecp_curves.d \
./platform/thinkey_security_al/mbedtls/source/entropy.d \
./platform/thinkey_security_al/mbedtls/source/entropy_poll.d \
./platform/thinkey_security_al/mbedtls/source/error.d \
./platform/thinkey_security_al/mbedtls/source/gcm.d \
./platform/thinkey_security_al/mbedtls/source/havege.d \
./platform/thinkey_security_al/mbedtls/source/hkdf.d \
./platform/thinkey_security_al/mbedtls/source/hmac_drbg.d \
./platform/thinkey_security_al/mbedtls/source/md.d \
./platform/thinkey_security_al/mbedtls/source/md2.d \
./platform/thinkey_security_al/mbedtls/source/md4.d \
./platform/thinkey_security_al/mbedtls/source/md5.d \
./platform/thinkey_security_al/mbedtls/source/memory_buffer_alloc.d \
./platform/thinkey_security_al/mbedtls/source/net_sockets.d \
./platform/thinkey_security_al/mbedtls/source/nist_kw.d \
./platform/thinkey_security_al/mbedtls/source/oid.d \
./platform/thinkey_security_al/mbedtls/source/padlock.d \
./platform/thinkey_security_al/mbedtls/source/pem.d \
./platform/thinkey_security_al/mbedtls/source/pk.d \
./platform/thinkey_security_al/mbedtls/source/pk_wrap.d \
./platform/thinkey_security_al/mbedtls/source/pkcs11.d \
./platform/thinkey_security_al/mbedtls/source/pkcs12.d \
./platform/thinkey_security_al/mbedtls/source/pkcs5.d \
./platform/thinkey_security_al/mbedtls/source/pkparse.d \
./platform/thinkey_security_al/mbedtls/source/pkwrite.d \
./platform/thinkey_security_al/mbedtls/source/platform.d \
./platform/thinkey_security_al/mbedtls/source/platform_util.d \
./platform/thinkey_security_al/mbedtls/source/poly1305.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_client.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_driver_wrappers.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_ecp.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_rsa.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_se.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_slot_management.d \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_storage.d \
./platform/thinkey_security_al/mbedtls/source/psa_its_file.d \
./platform/thinkey_security_al/mbedtls/source/ripemd160.d \
./platform/thinkey_security_al/mbedtls/source/rsa.d \
./platform/thinkey_security_al/mbedtls/source/rsa_internal.d \
./platform/thinkey_security_al/mbedtls/source/sha1.d \
./platform/thinkey_security_al/mbedtls/source/sha256.d \
./platform/thinkey_security_al/mbedtls/source/sha512.d \
./platform/thinkey_security_al/mbedtls/source/ssl_cache.d \
./platform/thinkey_security_al/mbedtls/source/ssl_ciphersuites.d \
./platform/thinkey_security_al/mbedtls/source/ssl_cli.d \
./platform/thinkey_security_al/mbedtls/source/ssl_cookie.d \
./platform/thinkey_security_al/mbedtls/source/ssl_msg.d \
./platform/thinkey_security_al/mbedtls/source/ssl_srv.d \
./platform/thinkey_security_al/mbedtls/source/ssl_ticket.d \
./platform/thinkey_security_al/mbedtls/source/ssl_tls.d \
./platform/thinkey_security_al/mbedtls/source/ssl_tls13_keys.d \
./platform/thinkey_security_al/mbedtls/source/threading.d \
./platform/thinkey_security_al/mbedtls/source/timing.d \
./platform/thinkey_security_al/mbedtls/source/version.d \
./platform/thinkey_security_al/mbedtls/source/version_features.d \
./platform/thinkey_security_al/mbedtls/source/x509.d \
./platform/thinkey_security_al/mbedtls/source/x509_create.d \
./platform/thinkey_security_al/mbedtls/source/x509_crl.d \
./platform/thinkey_security_al/mbedtls/source/x509_crt.d \
./platform/thinkey_security_al/mbedtls/source/x509_csr.d \
./platform/thinkey_security_al/mbedtls/source/x509write_crt.d \
./platform/thinkey_security_al/mbedtls/source/x509write_csr.d \
./platform/thinkey_security_al/mbedtls/source/xtea.d 

OBJS += \
./platform/thinkey_security_al/mbedtls/source/aes.o \
./platform/thinkey_security_al/mbedtls/source/aesni.o \
./platform/thinkey_security_al/mbedtls/source/ansi_x936_kdf.o \
./platform/thinkey_security_al/mbedtls/source/arc4.o \
./platform/thinkey_security_al/mbedtls/source/aria.o \
./platform/thinkey_security_al/mbedtls/source/asn1parse.o \
./platform/thinkey_security_al/mbedtls/source/asn1write.o \
./platform/thinkey_security_al/mbedtls/source/base64.o \
./platform/thinkey_security_al/mbedtls/source/bignum.o \
./platform/thinkey_security_al/mbedtls/source/blowfish.o \
./platform/thinkey_security_al/mbedtls/source/camellia.o \
./platform/thinkey_security_al/mbedtls/source/ccm.o \
./platform/thinkey_security_al/mbedtls/source/certs.o \
./platform/thinkey_security_al/mbedtls/source/chacha20.o \
./platform/thinkey_security_al/mbedtls/source/chachapoly.o \
./platform/thinkey_security_al/mbedtls/source/cipher.o \
./platform/thinkey_security_al/mbedtls/source/cipher_wrap.o \
./platform/thinkey_security_al/mbedtls/source/cmac.o \
./platform/thinkey_security_al/mbedtls/source/ctr_drbg.o \
./platform/thinkey_security_al/mbedtls/source/debug.o \
./platform/thinkey_security_al/mbedtls/source/des.o \
./platform/thinkey_security_al/mbedtls/source/dhm.o \
./platform/thinkey_security_al/mbedtls/source/ecdh.o \
./platform/thinkey_security_al/mbedtls/source/ecdsa.o \
./platform/thinkey_security_al/mbedtls/source/ecjpake.o \
./platform/thinkey_security_al/mbedtls/source/ecp.o \
./platform/thinkey_security_al/mbedtls/source/ecp_curves.o \
./platform/thinkey_security_al/mbedtls/source/entropy.o \
./platform/thinkey_security_al/mbedtls/source/entropy_poll.o \
./platform/thinkey_security_al/mbedtls/source/error.o \
./platform/thinkey_security_al/mbedtls/source/gcm.o \
./platform/thinkey_security_al/mbedtls/source/havege.o \
./platform/thinkey_security_al/mbedtls/source/hkdf.o \
./platform/thinkey_security_al/mbedtls/source/hmac_drbg.o \
./platform/thinkey_security_al/mbedtls/source/md.o \
./platform/thinkey_security_al/mbedtls/source/md2.o \
./platform/thinkey_security_al/mbedtls/source/md4.o \
./platform/thinkey_security_al/mbedtls/source/md5.o \
./platform/thinkey_security_al/mbedtls/source/memory_buffer_alloc.o \
./platform/thinkey_security_al/mbedtls/source/net_sockets.o \
./platform/thinkey_security_al/mbedtls/source/nist_kw.o \
./platform/thinkey_security_al/mbedtls/source/oid.o \
./platform/thinkey_security_al/mbedtls/source/padlock.o \
./platform/thinkey_security_al/mbedtls/source/pem.o \
./platform/thinkey_security_al/mbedtls/source/pk.o \
./platform/thinkey_security_al/mbedtls/source/pk_wrap.o \
./platform/thinkey_security_al/mbedtls/source/pkcs11.o \
./platform/thinkey_security_al/mbedtls/source/pkcs12.o \
./platform/thinkey_security_al/mbedtls/source/pkcs5.o \
./platform/thinkey_security_al/mbedtls/source/pkparse.o \
./platform/thinkey_security_al/mbedtls/source/pkwrite.o \
./platform/thinkey_security_al/mbedtls/source/platform.o \
./platform/thinkey_security_al/mbedtls/source/platform_util.o \
./platform/thinkey_security_al/mbedtls/source/poly1305.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_client.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_driver_wrappers.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_ecp.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_rsa.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_se.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_slot_management.o \
./platform/thinkey_security_al/mbedtls/source/psa_crypto_storage.o \
./platform/thinkey_security_al/mbedtls/source/psa_its_file.o \
./platform/thinkey_security_al/mbedtls/source/ripemd160.o \
./platform/thinkey_security_al/mbedtls/source/rsa.o \
./platform/thinkey_security_al/mbedtls/source/rsa_internal.o \
./platform/thinkey_security_al/mbedtls/source/sha1.o \
./platform/thinkey_security_al/mbedtls/source/sha256.o \
./platform/thinkey_security_al/mbedtls/source/sha512.o \
./platform/thinkey_security_al/mbedtls/source/ssl_cache.o \
./platform/thinkey_security_al/mbedtls/source/ssl_ciphersuites.o \
./platform/thinkey_security_al/mbedtls/source/ssl_cli.o \
./platform/thinkey_security_al/mbedtls/source/ssl_cookie.o \
./platform/thinkey_security_al/mbedtls/source/ssl_msg.o \
./platform/thinkey_security_al/mbedtls/source/ssl_srv.o \
./platform/thinkey_security_al/mbedtls/source/ssl_ticket.o \
./platform/thinkey_security_al/mbedtls/source/ssl_tls.o \
./platform/thinkey_security_al/mbedtls/source/ssl_tls13_keys.o \
./platform/thinkey_security_al/mbedtls/source/threading.o \
./platform/thinkey_security_al/mbedtls/source/timing.o \
./platform/thinkey_security_al/mbedtls/source/version.o \
./platform/thinkey_security_al/mbedtls/source/version_features.o \
./platform/thinkey_security_al/mbedtls/source/x509.o \
./platform/thinkey_security_al/mbedtls/source/x509_create.o \
./platform/thinkey_security_al/mbedtls/source/x509_crl.o \
./platform/thinkey_security_al/mbedtls/source/x509_crt.o \
./platform/thinkey_security_al/mbedtls/source/x509_csr.o \
./platform/thinkey_security_al/mbedtls/source/x509write_crt.o \
./platform/thinkey_security_al/mbedtls/source/x509write_csr.o \
./platform/thinkey_security_al/mbedtls/source/xtea.o 

SREC += \
THINKEY_RENESAS_DEMO_PROJECT.srec 

MAP += \
THINKEY_RENESAS_DEMO_PROJECT.map 


# Each subdirectory must supply rules for building sources it contributes
platform/thinkey_security_al/mbedtls/source/%.o: ../platform/thinkey_security_al/mbedtls/source/%.c
	$(file > $@.in,-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal  -g -D_RENESAS_RA_ -D_RA_CORE=CM33 -DPTX_PRODUCT_TYPE_IOT_READER -DPTX_FEATURES_NSC_READER_ONLY -DPTX_FEATURES_HAL_SPI -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/src" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra/fsp/inc" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra/fsp/inc/api" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra/fsp/inc/instances" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra/fsp/src/rm_freertos_port" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra/arm/CMSIS_5/CMSIS/Core/Include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra_gen" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra_cfg/fsp_cfg/bsp" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra_cfg/fsp_cfg" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra_cfg/aws" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/ra/aws/FreeRTOS/FreeRTOS/Source/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_bsp_al/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_debug_al/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_security_al/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_security_al/mbedtls/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_transport_al/PTX/COMMON" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_transport_al/PTX/FELICA_DTE" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/drivers/dwt_uwb_driver/Inc" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/task_node" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/Inc" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/config/default_config" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/srv/tag_list" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/CMSIS_RTOS" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/core/usb_uart_tx" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/srv/common_n" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/node" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/node/srv/msg_time" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/platform/thinkey_ranging_al/deca_source/platform_nrf52840/port" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/application/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/application/tab_app/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/common/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/dk_message_format/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/fast_transaction/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/fw_controller/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/owner_pairing/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/parse_format_commands/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/passive_entry/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/ranging/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/ranging/ral/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_abs/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_common/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/transport/core/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_data_access/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_digitalkey_applet/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_dk_creation/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_spake2/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/security/crypto_storage/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/transport/nal/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/framework/standard_transaction/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/transport/btal/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/transport/include" -I"C:/Users/jeeva/OneDrive/Desktop/Thinkseed/vehicle-gits2/platform/renesas/THINKEY_RENESAS_DEMO_PROJECT/../../../vehicle/include" -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

