################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
ASM_UPPER_DEPS := 
SX_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
platform/thinkey_bsp_al/source \
platform/thinkey_debug_al/source \
platform/thinkey_ranging_al/source \
platform/thinkey_security_al/mbedtls/source \
platform/thinkey_security_al \
platform/thinkey_storage_al/source \
platform/thinkey_transport_al/PTX/COMMON \
platform/thinkey_transport_al/PTX/FELICA_DTE \
platform/thinkey_transport_al/PTX/GPIO \
platform/thinkey_transport_al/PTX/HCE \
platform/thinkey_transport_al/PTX/IOT_READER \
platform/thinkey_transport_al/PTX/NATIVE_TAG \
platform/thinkey_transport_al/PTX/NDEF \
platform/thinkey_transport_al/PTX/NSC/NSC_CE \
platform/thinkey_transport_al/PTX/NSC/NSC_IOTRD \
platform/thinkey_transport_al/PTX/NSC/NSC_RD \
platform/thinkey_transport_al/PTX/NSC \
platform/thinkey_transport_al/PTX/PLAT/type2ab \
platform/thinkey_transport_al/PTX/RF_TEST \
platform/thinkey_transport_al/PTX \
platform/thinkey_transport_al/source \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang \
ra/board/ra6m5_ek \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_gpt \
ra/fsp/src/r_ioport \
ra/fsp/src/r_spi \
ra/fsp/src/rm_freertos_port \
ra_gen \
src/SEGGER_RTT \
src \
vehicle/application/murata_custom \
vehicle/application/source \
vehicle/application/tab_app/source \
vehicle/framework/dk_message_format/source \
vehicle/framework/fast_transaction/source \
vehicle/framework/fw_controller/source \
vehicle/framework/owner_pairing/source \
vehicle/framework/parse_format_commands/source \
vehicle/framework/passive_entry/source \
vehicle/framework/standard_transaction/source \
vehicle/ranging/source \
vehicle/security/crypto_abs/source \
vehicle/security/crypto_common/source \
vehicle/security/crypto_data_access/source \
vehicle/security/crypto_digitalkey_applet/source \
vehicle/security/crypto_dk_creation/source \
vehicle/security/crypto_spake2/source \
vehicle/transport/core/source \

